const crypto=require('node:crypto');
const CLIENT='7594138844-8nbveq6j7v7s4a88e0ikcp5tcgc2oi0u.apps.googleusercontent.com';
const C={1:'b2af8ba62f9342d6b7b3dfa4edd87166aac8dd5cdc8b6f2f11481f15b41e310a@group.calendar.google.com',2:'facf44bd6765cd27a89ac4baeaca7f275f9944bbb87c576399d09f9c581ee121@group.calendar.google.com'},CID=C[1];
const SCOPES='openid email profile https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/spreadsheets.readonly';
const hs=e=>Object.fromEntries(Object.entries(e.headers||{}).map(([k,v])=>[k.toLowerCase(),v]));
const cookies=e=>Object.fromEntries((hs(e).cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2));
function seal(s){let iv=crypto.randomBytes(12),k=crypto.createHash('sha256').update(process.env.COOKIE_SECRET).digest(),c=crypto.createCipheriv('aes-256-gcm',k,iv),ct=Buffer.concat([c.update(s,'utf8'),c.final()]),tag=c.getAuthTag();return Buffer.concat([iv,tag,ct]).toString('base64url')}
function open(v){try{let b=Buffer.from(v,'base64url'),iv=b.subarray(0,12),tag=b.subarray(12,28),ct=b.subarray(28),k=crypto.createHash('sha256').update(process.env.COOKIE_SECRET).digest(),d=crypto.createDecipheriv('aes-256-gcm',k,iv);d.setAuthTag(tag);return Buffer.concat([d.update(ct),d.final()]).toString()}catch{return''}}
const allowed=()=>{try{return JSON.parse(process.env.ALLOWED_USERS||'{}')}catch{return{}}};
const rsp=(statusCode,body,headers={})=>({statusCode,headers:{'Content-Type':'application/json; charset=utf-8',...headers},body:typeof body==='string'?body:JSON.stringify(body)});
const red=(location,cookie)=>({statusCode:302,headers:{Location:location,...(cookie?{'Set-Cookie':cookie}:{})},body:''});
const base=e=>process.env.PUBLIC_BASE_URL||('https://'+(hs(e)['x-forwarded-host']||hs(e).host||''));
const body=e=>{try{return JSON.parse(e.isBase64Encoded?Buffer.from(e.body||'','base64').toString():(e.body||'{}'))}catch{return{}}};
function addDays(s,n){let [y,m,d]=s.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n));return x.getUTCFullYear()+'-'+String(x.getUTCMonth()+1).padStart(2,'0')+'-'+String(x.getUTCDate()).padStart(2,'0')}
async function user(refresh){if(!refresh)return null;let r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:CLIENT,client_secret:process.env.GOOGLE_CLIENT_SECRET,refresh_token:refresh,grant_type:'refresh_token'})}),j=await r.json();if(!r.ok||!j.access_token)return null;let q=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:'Bearer '+j.access_token}}),p=await q.json();if(!q.ok||!p.email)return null;let role=allowed()[p.email.toLowerCase()]||null;if(!role){try{let a=await fetch('https://www.googleapis.com/calendar/v3/calendars/'+encodeURIComponent(CID)+'/events?privateExtendedProperty='+encodeURIComponent('eegUser='+p.email.toLowerCase())+'&maxResults=1',{headers:{Authorization:'Bearer '+j.access_token}}),z=await a.json();role=z.items?.[0]?.extendedProperties?.private?.eegRole||null}catch{}}return{email:p.email,name:p.name||p.email,picture:p.picture||'',role,access_token:j.access_token}}
const me=e=>user(open(cookies(e).eeg_google_refresh||''));
async function login(e){let state=crypto.randomUUID(),uri=base(e)+'/api/google/callback',u='https://accounts.google.com/o/oauth2/v2/auth?'+new URLSearchParams({client_id:CLIENT,redirect_uri:uri,response_type:'code',scope:SCOPES,access_type:'offline',prompt:'consent',include_granted_scopes:'true',state});return red(u,'eeg_oauth_state='+state+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=600')}
async function callback(e){let q=e.queryStringParameters||{},c=cookies(e);if(q.state!==c.eeg_oauth_state)return rsp(400,{error:'invalid_oauth_state'});let uri=base(e)+'/api/google/callback',r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code:q.code||'',client_id:CLIENT,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:uri,grant_type:'authorization_code'})}),j=await r.json();if(!r.ok||!j.refresh_token)return rsp(400,j);return red('/', 'eeg_google_refresh='+encodeURIComponent(seal(j.refresh_token))+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=15552000')}
async function session(e,token=false){let u=await me(e);if(!u)return rsp(401,token?{connected:false}:{authenticated:false});if(!u.role)return rsp(403,{authorized:false,connected:false,email:u.email});return rsp(200,token?{connected:true,access_token:u.access_token,role:u.role,email:u.email,name:u.name}:{authenticated:true,authorized:true,email:u.email,name:u.name,picture:u.picture,role:u.role})}
async function save(e){if((e.httpMethod||'GET')==='GET')return rsp(200,{version:'yandex-auto-v1',testDate:addDays('2026-10-04',1)});let u=await me(e);if(!u||!['admin','editor'].includes(u.role))return rsp(403,{error:'edit_required'});let x=body(e);if(!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||![1,2].includes(+x.room))return rsp(400,{error:'invalid_event'});let sd=x.date,ed=x.date,st=x.start,en=x.end;if(x.night){let h=Math.min(12,Math.max(8,+(x.nightHours||8)));st='20:00';ed=addDays(x.date,1);en=String((20+h)%24).padStart(2,'0')+':00'}let desc='Дата рождения: '+(x.birthDate||'')+'\nВозраст: '+(x.age||'')+'\nТип: '+(x.careType||'')+'\nТелефон: '+(x.phone||'')+'\nЦвет: '+(x.color||'')+'\nНочные часы: '+(x.nightHours||'')+'\nПСГ: '+(x.nightPSG?'1':'')+'\nКомментарий: '+(x.comment||''),p={summary:x.patient||'',description:desc,start:{dateTime:sd+'T'+st+':00+03:00'},end:{dateTime:ed+'T'+en+':00+03:00'}},b='https://www.googleapis.com/calendar/v3/calendars/'+encodeURIComponent(C[+x.room])+'/events',r=await fetch(x.googleId?b+'/'+encodeURIComponent(x.googleId):b,{method:x.googleId?'PUT':'POST',headers:{Authorization:'Bearer '+u.access_token,'Content-Type':'application/json'},body:JSON.stringify(p)}),j=await r.json();if(!r.ok)return rsp(r.status,{error:j?.error?.message||'calendar_error',start:p.start.dateTime,end:p.end.dateTime});return rsp(200,{ok:true,id:j.id,start:p.start.dateTime,end:p.end.dateTime})}
async function users(e){let u=await me(e);if(u?.role!=='admin')return rsp(403,{error:'admin_required'});let method=e.httpMethod||'GET',b='https://www.googleapis.com/calendar/v3/calendars/'+encodeURIComponent(CID)+'/events',H={Authorization:'Bearer '+u.access_token,'Content-Type':'application/json'};if(method==='GET'){let q=await fetch(b+'?q='+encodeURIComponent('__EEG_USER__')+'&timeMin=2026-01-01T00:00:00Z&timeMax=2031-01-01T00:00:00Z&singleEvents=true&maxResults=2500',{headers:H}),z=await q.json(),m=(z.items||[]).filter(x=>(x.summary||'').startsWith('__EEG_USER__')).map(x=>({id:x.id,email:x.extendedProperties?.private?.eegUser||'',role:x.extendedProperties?.private?.eegRole||'viewer'})),boot=Object.entries(allowed()).map(([email,role])=>({id:'bootstrap:'+email,email,role,bootstrap:true}));return rsp(200,{users:[...boot,...m.filter(x=>!boot.some(y=>y.email===x.email))]})}let x=body(e),email=String(x.email||'').trim().toLowerCase(),role=String(x.role||'viewer');if(method==='DELETE'){let q=await fetch(b+'?privateExtendedProperty='+encodeURIComponent('eegUser='+email)+'&maxResults=20',{headers:H}),z=await q.json();for(let i of z.items||[])await fetch(b+'/'+i.id,{method:'DELETE',headers:H});return rsp(200,{ok:true})}let q=await fetch(b+'?privateExtendedProperty='+encodeURIComponent('eegUser='+email)+'&maxResults=1',{headers:H}),z=await q.json(),old=z.items?.[0],p={summary:'__EEG_USER__ '+email,description:'Служебная запись доступа EEG Schedule',start:{dateTime:'2030-01-01T00:00:00+03:00'},end:{dateTime:'2030-01-01T00:05:00+03:00'},visibility:'private',transparency:'transparent',extendedProperties:{private:{eegUser:email,eegRole:role}}},r=await fetch(old?b+'/'+old.id:b,{method:old?'PUT':'POST',headers:H,body:JSON.stringify(p)});return r.ok?rsp(200,{ok:true,email,role}):rsp(r.status,await r.json())}
exports.handler=async e=>{try{let p=e.path||e.requestContext?.http?.path||'/',m=e.httpMethod||e.requestContext?.http?.method||'GET';e.httpMethod=m;if(p==='/api/google/login')return login(e);if(p==='/api/google/callback')return callback(e);if(p==='/api/google/token')return session(e,true);if(p==='/api/google/session')return session(e,false);if(p==='/api/google/logout')return rsp(200,{ok:true},{'Set-Cookie':'eeg_google_refresh=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'});if(p==='/api/users')return users(e);if(p==='/api/calendar/save'||p==='/health')return save(e);return rsp(404,{error:'not_found',path:p})}catch(err){console.error(err);return rsp(500,{error:'internal_error',message:err.message})}};
